name: ok great
author: Gianni Chiappetta
email: gianni@okgreat.ca
url: https://okgreat.ca
description: A dangerous place to idle.
lang: en-CA
github_url: https://github.com/gf3
bluesky_url: https://bsky.app/profile/bigstrongcoolguy.com
mastodon_url: https://mastodon.online/@gianni
